export const UserActionTypes = {
    SET_CURRENT_USER : 'SET_CURRENT_USER'
};
export const CartActionTypes = {
    TOGGLE_CART_DISPLAY : 'TOGGLE_CART_DISPLAY',
    ADD_ITEM : 'ADD_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM',
    REDUCE_ITEM_QUANTITY: 'REDUCE_ITEM_QUANTITY'
};
