export const UserActionTypes = {
    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'SIGNIN_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGNOUT_START: 'SIGNOUT_START',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',

};
export const CartActionTypes = {
    TOGGLE_CART_DISPLAY : 'TOGGLE_CART_DISPLAY',
    ADD_ITEM : 'ADD_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM',
    REDUCE_ITEM_QUANTITY: 'REDUCE_ITEM_QUANTITY',
    CLEAR_CART: 'CLEAR_CART',

};
export const ShopActionTypes = {
    FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE',
};

